# Generated by Django 4.0.4 on 2022-05-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('cost', models.IntegerField()),
                ('no_of_pages', models.IntegerField()),
                ('author', models.CharField(default='', max_length=200)),
                ('publisher', models.CharField(default='', max_length=70)),
                ('edition', models.IntegerField()),
            ],
        ),
    ]
